### ISSUE TITLE
Fix kramdown errors turning time-sequence diagrams in to aasvg

### ISSUE THREAD

**Issue by DDvO** [anima-wg/anima-brski-ae#27]
I had to revert for now the change to aasvg, to avoid the following kramdown errors.
How to fix this?
```
    Traceback (most recent call last):
            17: from /usr/local/bin/kramdown-rfc2629:23:in `<main>'
            16: from /usr/local/bin/kramdown-rfc2629:23:in `load'
            15: from /var/lib/gems/2.7.0/gems/kramdown-rfc2629-1.6.17/bin/kramdown-rfc2629:3:in `<top >
            14: from /usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:85:in `require'
            13: from /usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:85:in `require'
            12: from /var/lib/gems/2.7.0/gems/kramdown-rfc2629-1.6.17/lib/kramdown-rfc/command.rb:575:>
            11: from /var/lib/gems/2.7.0/gems/kramdown-2.4.0/lib/kramdown/document.rb:116:in `method_m>
            10: from /var/lib/gems/2.7.0/gems/kramdown-2.4.0/lib/kramdown/converter/base.rb:107:in `co>
             9: from /var/lib/gems/2.7.0/gems/kramdown-rfc2629-1.6.17/lib/kramdown-rfc2629.rb:323:in `>
             8: from /var/lib/gems/2.7.0/gems/kramdown-rfc2629-1.6.17/lib/kramdown-rfc2629.rb:328:in `>
             7: from /var/lib/gems/2.7.0/gems/kramdown-rfc2629-1.6.17/lib/kramdown-rfc2629.rb:1400:in >
             6: from /var/lib/gems/2.7.0/gems/kramdown-rfc2629-1.6.17/lib/kramdown-rfc2629.rb:340:in `>
             5: from /var/lib/gems/2.7.0/gems/kramdown-rfc2629-1.6.17/lib/kramdown-rfc2629.rb:333:in `>
             4: from /var/lib/gems/2.7.0/gems/kramdown-rfc2629-1.6.17/lib/kramdown-rfc2629.rb:333:in `>
             3: from /var/lib/gems/2.7.0/gems/kramdown-rfc2629-1.6.17/lib/kramdown-rfc2629.rb:335:in `>
             2: from /var/lib/gems/2.7.0/gems/kramdown-rfc2629-1.6.17/lib/kramdown-rfc2629.rb:619:in `>
             1: from /var/lib/gems/2.7.0/gems/kramdown-rfc2629-1.6.17/lib/kramdown-rfc2629.rb:463:in `>
    /var/lib/gems/2.7.0/gems/kramdown-rfc2629-1.6.17/lib/kramdown-rfc2629.rb:463:in `binread': No such>
            23: from /usr/local/bin/kramdown-rfc2629:23:in `<main>'
            22: from /usr/local/bin/kramdown-rfc2629:23:in `load'
            21: from /var/lib/gems/2.7.0/gems/kramdown-rfc2629-1.6.17/bin/kramdown-rfc2629:3:in `<top >
            20: from /usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:85:in `require'
            19: from /usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:85:in `require'
            18: from /var/lib/gems/2.7.0/gems/kramdown-rfc2629-1.6.17/lib/kramdown-rfc/command.rb:575:>
            17: from /var/lib/gems/2.7.0/gems/kramdown-2.4.0/lib/kramdown/document.rb:116:in `method_m>
            16: from /var/lib/gems/2.7.0/gems/kramdown-2.4.0/lib/kramdown/converter/base.rb:107:in `co>
            15: from /var/lib/gems/2.7.0/gems/kramdown-rfc2629-1.6.17/lib/kramdown-rfc2629.rb:323:in `>
            14: from /var/lib/gems/2.7.0/gems/kramdown-rfc2629-1.6.17/lib/kramdown-rfc2629.rb:328:in `>
            13: from /var/lib/gems/2.7.0/gems/kramdown-rfc2629-1.6.17/lib/kramdown-rfc2629.rb:1400:in >
            12: from /var/lib/gems/2.7.0/gems/kramdown-rfc2629-1.6.17/lib/kramdown-rfc2629.rb:340:in `>
            11: from /var/lib/gems/2.7.0/gems/kramdown-rfc2629-1.6.17/lib/kramdown-rfc2629.rb:333:in `>
            10: from /var/lib/gems/2.7.0/gems/kramdown-rfc2629-1.6.17/lib/kramdown-rfc2629.rb:333:in `>
             9: from /var/lib/gems/2.7.0/gems/kramdown-rfc2629-1.6.17/lib/kramdown-rfc2629.rb:335:in `>
             8: from /var/lib/gems/2.7.0/gems/kramdown-rfc2629-1.6.17/lib/kramdown-rfc2629.rb:619:in `>
             7: from /var/lib/gems/2.7.0/gems/kramdown-rfc2629-1.6.17/lib/kramdown-rfc2629.rb:462:in `>
             6: from /var/lib/gems/2.7.0/gems/kramdown-rfc2629-1.6.17/lib/kramdown-rfc2629.rb:466:in `>
             5: from /var/lib/gems/2.7.0/gems/kramdown-rfc2629-1.6.17/lib/kramdown-rfc2629.rb:466:in `>
             4: from /var/lib/gems/2.7.0/gems/kramdown-rfc2629-1.6.17/lib/kramdown-rfc2629.rb:517:in `>
             3: from /usr/lib/ruby/2.7.0/open3.rb:281:in `capture3'
             2: from /usr/lib/ruby/2.7.0/open3.rb:101:in `popen3'
             1: from /usr/lib/ruby/2.7.0/open3.rb:213:in `popen_run'
    /usr/lib/ruby/2.7.0/open3.rb:213:in `spawn': No such file or directory - aasvg (Errno::ENOENT)
    *** kramdown-rfc failed, status 1
```

**Comment by mcr** [comment]
I think you need
   node install aasvg

dooku-[~](2.6.6) mcr 5558 %file /usr/local/bin/aasvg
/usr/local/bin/aasvg: symbolic link to ../lib/node_modules/aasvg/main.js

**Comment by DDvO** [comment]
Thanks for the hint - 
```
npm install -g aasvg
```
did the trick.
